
version: '3.9'

services: 

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:1.1.0
    network_mode: bridge
    environment:
      - node.name=opensearch
      - cluster.name=opensearch-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/opensearch/data

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_CUSTOM_BACKEND=http://opensearch:9200
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    links:
      - opensearch

  # localstack:
  #   container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
  #   image: localstack/localstack:latest
  #   network_mode: bridge
  #   depends_on:
  #     - opensearch
  #   environment: 
  #     - AWS_DEFAULT_REGION=us-east-1
  #     - EDGE_PORT=4566
  #     - SERVICES=s3
  #     - OPENSEARCH_CUSTOM_BACKEND=http://opensearch:9200
  #     - DEBUG=${DEBUG- }
  #     - DATA_DIR=${DATA_DIR- }
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #     - HOST_TMP_FOLDER=${TMPDIR}
  #   ports: 
  #     - '4566'
  #   volumes: 
  #     - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   links:
  #     - opensearch

volumes:
  data01:
    driver: local